### ISSUE TITLE
Zeiler pretrained model availability

### ISSUE THREAD

**Issue by Parry26** [fmassa/object-detection.torch#16]
The link given to the pretrained Zeiler CNN is linking to a mat file. Is the pretrained model available anywhere as a t7?

https://drive.google.com/file/d/0B-TTdm1WNtybdzdMUHhLc05PSE0/view?pref=2&pli=1

**Comment by fmassa** [comment]
You can load the `.mat` file with all the model definition by calling the [createModel function in zeiler.lua](https://github.com/fmassa/object-detection.torch/blob/refactoring/models/zeiler.lua). It doesn't require you to have matlab installed, only `matio`, and the size of the file is smaller than if it was saved in torch format (because of the compression).
Is that ok for you ?

**Comment by Parry26** [comment]
Thanks Francisco, that's great.

J

On 30 Jan 2016, at 10:17 PM, Francisco Massa <notifications@github.com<mailto:notifications@github.com>> wrote:

You can load the .mat file with all the model definition by calling the createModel function in zeiler.luahttps://github.com/fmassa/object-detection.torch/blob/refactoring/models/zeiler.lua. It doesn't require you to have matlab installed, only matio, and the size of the file is smaller than if it was saved in torch format (because of the compression).
Is that ok for you ?

##

**Comment by fmassa** [comment]
I'm closing the issue, feel free to re-open it if it's not enough for you.
