### ISSUE TITLE
Is the code ready for COCO dataset? if not.. what part is required to be developed..?

### ISSUE THREAD

**Issue by kgohil** [fmassa/object-detection.torch#20]

**Comment by fmassa** [comment]
The code for parsing COCO dataset was never completely finished. I did some initial tests with it, but never a full test on the dataset, so there might be things that need to be fixed.
As it has been a while since I haven't touched the COCO dataset, I don't really remember what was missing. But the first thing I'd try would be to see if `dataset:attachProposals(i)` work, as it is the requirement for the `BatchProviders` to be able to sample minibatches from the dataset.
